apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service1
  name: service1
spec:
  containers:
  - image: nginx
    name: service1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
