apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service2
  name: service2
spec:
  containers:
  - image: httpd
    name: service2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
