apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: service1
  name: service1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: service1
status:
  loadBalancer: {}
